### ISSUE TITLE
Exclude test folder from published package

### ISSUE THREAD

**Issue by nutstick** [snyk/composer-lockfile-parser#13]
Hi, I run into a flow issue after I try to integrate `@sentry/react-native` into my project which is internally use your package.

```
$ flow
Error --------- ../sdk/node_modules/@snyk/composer-lockfile-parser/test/fixtures/composer-invalid-json/composer.json:2:2

Unexpected token ,

   2| 	,"name" : "adodb/adodb-php",
```

I believe that `/test` folder is use only for testing purpose. Can you help exclude it from published package? 

### Expected behaviour

`/test` is excluded from published package.

### Actual behaviour

`/test` is included from published package.

### Steps to reproduce

- create new project and use `flow` as type checker
- install this pacakge
- run `flow` check

---

### Solution

specific `files` in `package.json`

```
"files": [
  "dist"
],
```

**Comment by gitphill** [comment]
@nutstick thank you for submitting this issue, I've raised https://github.com/snyk/composer-lockfile-parser/pull/17

**Comment by gitphill** [comment]
Fixed in https://github.com/snyk/composer-lockfile-parser/releases/tag/v1.1.1

**Comment by nutstick** [comment]
Thanks @gitphill
